version: '3.1'

services:
  db:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD_FILE: /run/secrets/db_password
      POSTGRES_ROOT_PASSWORD_FILE: /run/secrets/db_password
      POSTGRES_USER: bagelReader
      # just putting this here so that I know the default DB
      POSTGRES_DB: bagelReader
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - ./volumes/db:/var/lib/postgresql/data
    ports: 
      - 127.0.0.1:5432:5432
    secrets:
      - db_password

  web:
    image: nginx:1-alpine
    restart: always
    volumes:
      - ./web/html:/usr/share/nginx/html
    ports: 
      - 127.0.0.1:80:80
      - 127.0.0.1:443:443

  api:
    image: alpine:3
    # restart: always 
    entrypoint: /entrypoint.sh
    environment:
      POSTGRES_PORT: 5432
      POSTGRES_USER: bagelReader
      POSTGRES_DB: bagelReader
    volumes:
      - ./api/bagelReader:/usr/bin/bagelReader
      - ./api/entrypoint.sh:/entrypoint.sh
    secrets:
      - db_password

secrets:
  db_password:
    file: secrets/dbpw.txt

